"""
Term-wide Staff Payroll PDF Report Generator.

Renders a printable full-term backup report for Director record-keeping.
"""

import logging
import os
from datetime import datetime, timezone

from fpdf import FPDF
from fpdf.enums import XPos, YPos

from app.schemas.payroll import StaffPayrollSummary
from app.utils.formatting import kobo_to_naira

logger = logging.getLogger(__name__)

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
_LOGO_PATH = os.path.join(_REPO_ROOT, "frontend", "assets", "images", "jummikville_logo.jpeg")


def _naira(amount_kobo: int) -> str:
    return f"NGN {amount_kobo / 100:,.2f}"


def render_term_payroll_pdf(
    summary: StaffPayrollSummary,
    term_name: str,
    director_email: str,
    school_name: str = "Jummikville Academy",
) -> bytes:
    """
    Render a printable term payroll report PDF.
    """
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # 1. Header & Logo
    if os.path.isfile(_LOGO_PATH):
        try:
            pdf.image(_LOGO_PATH, x=15, y=12, w=20)
            pdf.set_x(38)
        except Exception:
            pdf.set_x(15)
    else:
        pdf.set_x(15)

    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 7, school_name, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_x(38 if os.path.isfile(_LOGO_PATH) else 15)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(
        0, 5,
        f"OFFICIAL STAFF PAYROLL BACKUP REPORT - {term_name}",
        new_x=XPos.LMARGIN, new_y=YPos.NEXT
    )
    pdf.ln(6)

    # 2. Title Banner
    pdf.set_fill_color(30, 58, 138)  # brand blue
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 9, f"  TERM PAYROLL SUMMARY ({term_name.upper()})", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    # 3. Summary Cards Table
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 9)

    col_w = 45
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(col_w, 6, "Total Staff:")
    pdf.cell(col_w, 6, "Scheduled Salary:")
    pdf.cell(col_w, 6, "Total Salary Paid:")
    pdf.cell(col_w, 6, "Total Outstanding:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("Helvetica", "", 10)
    pdf.cell(col_w, 6, str(summary.total_staff))
    pdf.cell(col_w, 6, _naira(summary.total_scheduled_kobo))
    pdf.cell(col_w, 6, _naira(summary.total_paid_kobo))
    pdf.cell(col_w, 6, _naira(summary.total_remaining_kobo), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(6)

    # 4. Staff Payroll Table Header
    pdf.set_fill_color(241, 245, 249)
    pdf.set_font("Helvetica", "B", 8)
    pdf.cell(40, 7, " Staff Name", fill=True)
    pdf.cell(30, 7, "Role", fill=True)
    pdf.cell(30, 7, "Classes Taught", fill=True)
    pdf.cell(28, 7, "Scheduled", fill=True, align="R")
    pdf.cell(28, 7, "Paid Out", fill=True, align="R")
    pdf.cell(24, 7, "Status ", fill=True, align="R", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("Helvetica", "", 8)
    for r in summary.records:
        classes_str = ", ".join(r.classes_taught) if r.classes_taught else "-"
        if len(classes_str) > 20:
            classes_str = classes_str[:18] + ".."

        pdf.cell(40, 6, f" {r.staff_name[:22]}")
        pdf.cell(30, 6, f"{r.role_title[:18]}")
        pdf.cell(30, 6, classes_str)
        pdf.cell(28, 6, _naira(r.amount_scheduled_kobo), align="R")
        pdf.cell(28, 6, _naira(r.amount_paid_kobo), align="R")
        pdf.cell(24, 6, f"{r.status.upper()} ", align="R", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.ln(10)

    # 5. Footer & Signoff
    now_str = datetime.now(timezone.utc).strftime("%d %b %Y, %H:%M UTC")
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 5, f"Report Generated: {now_str} | Generated by Director: {director_email}", align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    return bytes(pdf.output())
